// Shared CPU/HLSL Ground Response constants. Keep this preprocessor-only so the
// gameplay resistance path and TerrainSurface shader cannot quietly diverge.
#define PIXL_GR_SNOW_FINE_VARIATION 0.10f
#define PIXL_GR_SNOW_POCKET_STRENGTH 0.22f
#define PIXL_GR_SNOW_FINE_SCALE 180.0f
#define PIXL_GR_SNOW_POCKET_SCALE 620.0f
#define PIXL_GR_SNOW_MOUND_STRENGTH 0.32f
#define PIXL_GR_SNOW_MOUND_SCALE 300.0f
#define PIXL_GR_SNOW_MOUND_DETAIL_SCALE 170.0f
#define PIXL_GR_SNOW_MAX_PRISTINE_HEIGHT 72.0f
#define PIXL_GR_SNOW_DEEP_DRIFT_SCALE 560.0f
#define PIXL_GR_SNOW_DEEP_DRIFT_DETAIL_SCALE 290.0f
#define PIXL_GR_SNOW_DEEP_DRIFT_BLUR_RADIUS 120.0f
#define PIXL_GR_SNOW_MOUND_BLUR_RADIUS 58.0f
#define PIXL_GR_SNOW_WIND_X 0.8192319f
#define PIXL_GR_SNOW_WIND_Y 0.5734623f
#define PIXL_GR_MUD_FINE_VARIATION 0.08f
#define PIXL_GR_MUD_POCKET_STRENGTH 0.16f
#define PIXL_GR_MUD_FINE_SCALE 200.0f
#define PIXL_GR_MUD_POCKET_SCALE 480.0f
#define PIXL_GR_MUD_WETNESS_LOWER_BAND 0.22f
#define PIXL_GR_MUD_WETNESS_UPPER_BAND 0.18f
#define PIXL_GR_SHORELINE_BELOW_WATER_FADE 2.0f
#define PIXL_GR_SHORELINE_ABOVE_WATER_FULL 5.0f
#define PIXL_GR_SHORELINE_ABOVE_WATER_FADE 64.0f
