[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$out = Join-Path $repo 'docs\release_polish\SOURCE_PROVENANCE_MATRIX.md'
$prePixl = 'dcea14b61396fd5544aa5f0ad2165c24aa0d8816'

$extensions = @('.cpp', '.h', '.hpp', '.hlsl', '.hlsli', '.cmake', '.ps1', '.bat')
$rootDocs = @('ATTRIBUTION.md', 'AUTHORS.md', 'COPYING', 'EXCEPTIONS.md', 'NOTICE.md',
    'README.md', 'THIRD_PARTY_NOTICES.md', 'TRADEMARKS.md', 'distribution/SOURCE-AND-CREDITS.md')
$tracked = @(& git -C $repo ls-files)
$untracked = @(& git -C $repo ls-files --others --exclude-standard)
$files = @($tracked + $untracked | Sort-Object -Unique | Where-Object {
    $ext = [IO.Path]::GetExtension($_).ToLowerInvariant()
    $_ -in $rootDocs -or $ext -in $extensions -or $_ -match '(^|/)CMakeLists\.txt$'
})

$ancestor = @{}
& git -C $repo ls-tree -r $prePixl | ForEach-Object {
    if ($_ -match '^(\S+)\s+blob\s+(\S+)\t(.+)$') { $ancestor[$matches[3]] = $matches[2] }
}

function Test-Pattern([string]$Path, [string[]]$Patterns) {
    foreach ($pattern in $Patterns) { if ($Path -like $pattern) { return $true } }
    return $false
}

$thirdParty = @(
    'extern/*', '*Streamline*', '*FidelityFX*', '*bend_sss_*', '*optimized-ggx.hlsli',
    '*SeparableSSS.hlsli', '*Spherical Harmonics/*', '*XeGTAO*', '*SmoothCamAPI.h',
    'distribution/Interface/PIXLRenderer/Fonts/*'
)
$pixlOriginal = @(
    'engine/Modules/ContainedLiquid*', 'pipeline/Contained Liquids/*',
    'engine/Modules/DistantLife.*', 'pipeline/Distant Life/*',
    'engine/Modules/WindowLife.*', 'pipeline/WindowLife/Kernels/WindowLife/WindowLife.hlsli',
    'engine/Renderer/RenderOrigin.*', 'distribution/Shaders/Common/PIXLRenderOrigin.hlsli',
    'engine/Modules/CurvedSurfaceMapping.*', 'pipeline/Curved Surface Mapping/*',
    'engine/Director/DirectorCameraPath.*',
    'pipeline/Camera Suite/Kernels/CameraSuite/DOF*',
    'pipeline/Camera Suite/Kernels/CameraSuite/DofControl.hlsli',
    'pipeline/Rain Response/Kernels/RainResponse/Precipitation.hlsli',
    'pipeline/Rain Response/Kernels/RainResponse/RoofRunoff*',
    'pipeline/Rain Response/Kernels/RainResponse/WorldPrecipitation.hlsli',
    'pipeline/Ground Response/Kernels/GroundResponse/Surface*',
    'pipeline/Ground Response/Kernels/GroundResponse/TerrainSurface.hlsl',
    'pipeline/Ground Response/Kernels/GroundResponse/GroundMarkUpdateCS.hlsl'
)
$derived = @(
    'engine/*', 'pipeline/*', 'distribution/Shaders/*', 'cmake/*', 'CMakeLists.txt',
    'CMakePresets.json', 'Build*.bat', 'DeployPIXL.bat', 'tools/*'
)

$rows = [Collections.Generic.List[object]]::new()
foreach ($relative in $files) {
    $path = Join-Path $repo ($relative -replace '/', '\')
    if (!(Test-Path -LiteralPath $path -PathType Leaf)) { continue }
    $classification = 'E'
    $basis = 'Mixed or uncertain provenance; retain history and all notices.'

    if (Test-Pattern $relative $thirdParty) {
        $classification = 'D'
        $basis = 'Third-party/vendor path or file-local third-party notice.'
    } elseif (Test-Pattern $relative $pixlOriginal) {
        $classification = 'C'
        $basis = 'PIXL-created path supported by the PIXL checkpoint/later history; shared infrastructure remains derived.'
    } elseif ($ancestor.ContainsKey($relative)) {
        $worktreeHash = (& git -C $repo hash-object -- $relative).Trim()
        if ($worktreeHash -eq $ancestor[$relative]) {
            $classification = 'A'
            $basis = 'Blob matches the retained pre-PIXL Community Shaders ancestor.'
        } else {
            $classification = 'B'
            $basis = 'Path exists in the retained pre-PIXL ancestor and now differs.'
        }
    } elseif (Test-Pattern $relative $derived) {
        $classification = 'B'
        $basis = 'Located in an upstream-derived subsystem; PIXL changes/import history require retained upstream credit.'
    }
    $rows.Add([pscustomobject]@{ Path = $relative; Class = $classification; Basis = $basis })
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# PIXL Renderer source provenance matrix')
$lines.Add('')
$lines.Add('Generated by `tools/WriteSourceProvenanceAudit.ps1` from the current worktree and retained Git ancestor `dcea14b61396fd5544aa5f0ad2165c24aa0d8816`. Classification is deliberately conservative: ambiguity is E, and module-level PIXL originality never erases upstream infrastructure or embedded notices.')
$lines.Add('')
$lines.Add('- A: upstream/unmodified at the retained same-path blob')
$lines.Add('- B: upstream-derived and modified/integrated by PIXL')
$lines.Add('- C: PIXL-created implementation supported by repository history')
$lines.Add('- D: third-party/vendor code or separately licensed material')
$lines.Add('- E: mixed or uncertain provenance requiring notice preservation')
$lines.Add('')
$counts = $rows | Group-Object Class | Sort-Object Name
$lines.Add('## Counts')
$lines.Add('')
$lines.Add('| Class | Files |')
$lines.Add('|---|---:|')
foreach ($count in $counts) { $lines.Add("| $($count.Name) | $($count.Count) |") }
$lines.Add('')
$lines.Add('## File ledger')
$lines.Add('')
$lines.Add('| Class | Path | Evidence basis |')
$lines.Add('|---|---|---|')
foreach ($row in $rows) {
    $safePath = $row.Path.Replace('|', '\|')
    $lines.Add("| $($row.Class) | ``$safePath`` | $($row.Basis) |")
}
$lines.Add('')
$lines.Add('A generated classification does not override a file-local copyright or licence notice. Review `SOURCE_PROVENANCE_AUDIT.md` for module ancestry and known uncertainties.')

[IO.File]::WriteAllLines($out, $lines)
Write-Host "Wrote $($rows.Count) provenance rows to $out"
