[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$output = Join-Path $repo 'docs\release_polish'
New-Item -ItemType Directory -Path $output -Force | Out-Null

$tracked = @(& git -C $repo ls-files -- engine pipeline distribution installer tools cmake CMakeLists.txt CMakePresets.json BuildRelease.bat BuildDeployAll.bat DeployPIXL.bat)
$untracked = @(& git -C $repo ls-files --others --exclude-standard -- engine pipeline distribution installer tools cmake)
if ($LASTEXITCODE -ne 0) { throw 'Cannot enumerate release files.' }
$files = @($tracked + $untracked | Sort-Object -Unique)
$baseline = (& git -C $repo merge-base HEAD main).Trim()
if ($LASTEXITCODE -ne 0 -or !$baseline) { $baseline = (& git -C $repo rev-parse HEAD).Trim() }
$committedChanged = @(& git -C $repo diff --name-only $baseline HEAD -- engine pipeline distribution installer tools cmake CMakeLists.txt CMakePresets.json BuildRelease.bat BuildDeployAll.bat DeployPIXL.bat)
$worktreeChanged = @(& git -C $repo status --porcelain=v1 --untracked-files=all | ForEach-Object { $_.Substring(3).Trim('"') -replace '\\','/' })
$modified = @($committedChanged + $worktreeChanged | Sort-Object -Unique)
$textExtensions = @('.cpp','.h','.hpp','.hlsl','.hlsli','.ini','.json','.xml','.ps1','.bat','.txt','.cmake','.md','.in','.rc','.fx','.fxh','.csv','.svg')
$sourceExtensions = @('.cpp','.h','.hpp','.hlsl','.hlsli','.fx','.fxh')
$matrix = [Collections.Generic.List[string]]::new()
$details = [Collections.Generic.List[string]]::new()
$inventory = [Collections.Generic.List[string]]::new()
$matrix.Add('# PIXL 1.0.4 file review matrix')
$matrix.Add('')
$matrix.Add("Generated by ``tools/WriteReleasePolishInventory.ps1``. Modified compares the release branch and worktree with baseline $baseline. This script loads text and searches patterns; it does not perform a semantic file review or trace call paths. Semantic review stays unverified until file-level evidence is recorded separately.")
$matrix.Add('')
$matrix.Add('| Path | Subsystem | Active | Automated scan | Semantic review | Modified | Security | Fidelity | Performance | Future suggestions |')
$matrix.Add('|---|---|---|---|---|---|---|---|---|---|---|')
$details.Add('# PIXL 1.0.4 per-file automated inventory')
$details.Add('')
$details.Add('This is a reproducible inventory and pattern scan, not a completed per-file engineering review. Findings marked `pattern` require manual tracing. Runtime and visual validation are recorded separately.')
$inventory.Add('# PIXL 1.0.4 active build inventory')
$inventory.Add('')
$inventory.Add('Source roots: `engine`, `pipeline`, `distribution`, `installer`, `tools`, `cmake`, and root build/deployment entry points. Third-party submodules and historical `dist` output are excluded from this PIXL-owned inventory.')
$inventory.Add('')
$inventory.Add('| Subsystem | Active files | Retired files |')
$inventory.Add('|---|---:|---:|')
$counts = @{}
foreach ($relative in $files) {
    $path = Join-Path $repo $relative.Replace('/','\')
    if (!(Test-Path -LiteralPath $path -PathType Leaf)) { continue }
    $extension = [IO.Path]::GetExtension($relative).ToLowerInvariant()
    $subsystem = ($relative -split '/')[0]
    if ($subsystem -eq 'pipeline') { $subsystem = ($relative -split '/')[1] }
    elseif ($subsystem -eq 'engine' -and ($relative -split '/').Length -ge 3) { $subsystem = 'engine/' + ($relative -split '/')[1] }
    $active = $true
    if ($relative -like 'pipeline/*') {
        $moduleDir = ($relative -split '/')[1]
        $descriptor = Join-Path $repo "pipeline\$moduleDir\Module.ini"
        if ((Test-Path -LiteralPath $descriptor) -and (Get-Content -LiteralPath $descriptor -Raw) -match '(?im)^\s*Pipeline\s*=\s*Retired\s*$') { $active = $false }
    }
    if (!$counts.ContainsKey($subsystem)) { $counts[$subsystem] = @{ Active = 0; Retired = 0 } }
    if ($active) { $counts[$subsystem].Active++ } else { $counts[$subsystem].Retired++ }
    $isText = $extension -in $textExtensions -or $relative -eq 'CMakeLists.txt' -or $relative -like '*.bat'
    $content = if ($isText) { [IO.File]::ReadAllText($path) } else { '' }
    $lineCount = if ($isText) { ([regex]::Matches($content,"`n")).Count + 1 } else { 0 }
    $deps = if ($extension -in $sourceExtensions) {
        @([regex]::Matches($content,'(?m)^\s*#\s*include\s*[<"]([^>"]+)[>"]') | Select-Object -First 12 | ForEach-Object { $_.Groups[1].Value })
    } else { @() }
    $signals = [Collections.Generic.List[string]]::new()
    if ($content -match '(?i)TODO|FIXME|WIP|temporary|placeholder') { $signals.Add('unfinished-marker') }
    if ($content -match '(?i)LoadLibrary|GetProcAddress|Start-Process|Invoke-Expression|CreateProcess|ShellExecute') { $signals.Add('dynamic-load/process-call') }
    if ($content -match '(?i)https?://|winhttp|winsock|curl|download') { $signals.Add('network-or-documentation-reference') }
    if ($content -match '(?i)normalize\s*\(|rsqrt\s*\(|log2?\s*\(|pow\s*\(') { $signals.Add('numerical-domain-review') }
    if ($content -match '(?i)register\s*\([tusb][0-9]+\)|SetShaderResources|SetUnorderedAccessViews') { $signals.Add('binding-review') }
    $kind = if ($extension -in @('.hlsl','.hlsli','.fx','.fxh')) { 'shader stage/include' }
            elseif ($extension -eq '.cpp') { 'C++ implementation' }
            elseif ($extension -in @('.h','.hpp')) { 'C++ interface' }
            elseif ($extension -in @('.ps1','.bat')) { 'build/deployment tool' }
            elseif ($extension -in @('.ini','.json','.xml')) { 'configuration/metadata' }
            else { 'runtime asset/build input' }
    $review = if ($isText) { 'Static scan' } else { 'Metadata scan' }
    $modifiedFlag = if ($relative -in $modified) { 'Yes' } else { 'No' }
    $security = if (!$isText) { 'Binary/asset metadata' } elseif ($signals -contains 'dynamic-load/process-call') { 'Manual trace required' } else { 'Static pattern scan' }
    $fidelity = if ($extension -in @('.hlsl','.hlsli','.fx','.fxh')) { 'Shader review queued' } else { 'No direct shader output / trace owner' }
    $performance = if ($extension -in $sourceExtensions) { 'Call-path review queued' } else { 'Packaging/asset review' }
    $future = if ($signals.Count) { ($signals -join ', ') } else { 'None from static scan' }
    $safePath = $relative.Replace('|','\|')
    $matrix.Add("| ``$safePath`` | $subsystem | $(if($active){'Yes'}else{'Retired'}) | $review | Not verified in this matrix | $modifiedFlag | $security | $fidelity | $performance | $future |")
    $details.Add('')
    $details.Add("## ``$relative``")
    $details.Add("- Purpose/participation: $kind in $subsystem; $(if($active){'active build/runtime candidate'}else{'retired module input'}).")
    $details.Add("- Dependencies visible in file: $(if($deps.Count){$deps -join ', '}else{'none in direct includes'}).")
    $details.Add("- Current implementation quality: not assessed by this script ($lineCount text lines loaded); semantic/runtime quality requires the owning module trace.")
    $details.Add("- Fidelity opportunity: $(if($extension -in @('.hlsl','.hlsli')){'check numerical domains, material semantics, temporal stability'}else{'inspect consuming shader/module before altering visual output'}).")
    $details.Add("- Performance opportunity: $(if($extension -in $sourceExtensions){'inspect invocation cadence and redundant work'}else{'check payload size and runtime need'}).")
    $details.Add("- Correctness/stability findings: $(if($signals.Count){$signals -join ', '}else{'no static pattern flagged'}).")
    $details.Add("- Security findings: $security; no conclusion about safety is inferred solely from pattern absence.")
    $details.Add('- Maintainability: retain existing ownership and call path unless a verified issue justifies a change.')
    $details.Add("- Changes implemented: $(if($modifiedFlag -eq 'Yes'){'file differs from HEAD; see Git diff for ownership and details'}else{'none in this pass'}).")
    $details.Add('- Changes rejected: none proposed by the static scan alone.')
    $details.Add("- Future improvements: $future; validate against module-level review before implementation.")
    $details.Add('- Validation: automated enumeration/pattern scan only; semantic, compile and runtime validation are separate gates.')
}
foreach ($entry in $counts.GetEnumerator() | Sort-Object Name) {
    $inventory.Add("| $($entry.Name.Replace('|','\|')) | $($entry.Value.Active) | $($entry.Value.Retired) |")
}
$inventory.Add('')
$inventory.Add("Total enumerated files: $($files.Count). Check Git status for files added after this report and rerun the script before release.")
$matrix.Add('')
$matrix.Add('No file is marked semantically reviewed by this generator. File-level review requires separate evidence; the exhaustive-review release gate remains open.')
[IO.File]::WriteAllLines((Join-Path $output 'FILE_REVIEW_MATRIX.md'), $matrix)
[IO.File]::WriteAllLines((Join-Path $output 'PER_FILE_STATIC_REVIEW.md'), $details)
[IO.File]::WriteAllLines((Join-Path $output 'ACTIVE_BUILD_INVENTORY.md'), $inventory)
Write-Host "Wrote inventory for $($files.Count) files to $output"
